apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubeimage1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeimage1
  template:
    metadata:
      labels:
        app: kubeimage1 
    spec:
      containers:
        - name: kubeimage1 
          image: cont00regs003.azurecr.io/kubeimage1
          ports:
          - containerPort: 80